import React, { useEffect, useState } from "react";

export default function Reports() {
  const [families, setFamilies] = useState([]);

  useEffect(() => {
    const fetchFamilies = async () => {
      try {
        const res = await fetch("http://localhost:5000/api/incidents/with-families");
        const data = await res.json();
        setFamilies(data.families || []);
      } catch (e) {
        console.error("Error fetching families:", e);
      }
    };

    fetchFamilies();
  }, []);

  const handleExportCaseFile = (family) => {
    const content = `
AURASCAN CASE FILE REPORT
Generated: ${new Date().toLocaleString()}

FAMILY: ${family.label}
SCAM TYPE: ${family.scamType}
RISK LEVEL: ${family.risk || family.threat_level}
CASES LINKED: ${family.cases.length}

EVOLUTION STAGE: ${family.evolution_stage}
THREAT LEVEL: ${family.threat_level}

CORE MARKERS:
${(family.coreMarkers || []).join(", ")}

INSIGHTS:
${(family.insights || []).map(i => `- ${i}`).join("\n")}

SUGGESTED ACTIONS:
${(family.actions || []).map(a => `• ${a}`).join("\n")}

EVIDENCE ARTIFACTS:
Phones: ${(family.artifacts?.phones || []).join(", ") || "None"}
URLs: ${(family.artifacts?.urls || []).join(", ") || "None"}

Generated by AuraScan Intelligence Engine
    `;

    const element = document.createElement("a");
    element.setAttribute("href", "data:text/plain;charset=utf-8," + encodeURIComponent(content));
    element.setAttribute("download", `${family.label.replace(/\s+/g, "_")}_report.txt`);
    element.style.display = "none";
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  return (
    <div style={{ padding: 20, height: '100%', overflowY: 'auto' }}>
      <h2 style={{ fontFamily: 'var(--font-mono)', color: 'var(--accent-primary)', marginBottom: 20 }}>
        CASE FILE REPORTS
      </h2>

      {families.length === 0 ? (
        <div style={{ color: 'var(--text-secondary)', fontFamily: 'var(--font-mono)' }}>
          No case files available. Submit incidents to generate reports.
        </div>
      ) : (
        families.map((fam, idx) => (
          <div key={idx} style={{
            background: 'rgba(0, 0, 0, 0.4)',
            border: '1px solid var(--border-color)',
            borderRadius: 4,
            padding: 12,
            marginBottom: 12
          }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 }}>
              <div>
                <div style={{ fontFamily: 'var(--font-mono)', fontWeight: 800, color: 'var(--accent-primary)' }}>
                  {fam.label}
                </div>
                <div style={{ fontSize: 11, color: 'var(--text-secondary)' }}>
                  {fam.scamType} • {fam.cases.length} incidents
                </div>
              </div>
              <div style={{ display: 'flex', gap: 8 }}>
                <span style={{
                  fontFamily: 'var(--font-mono)',
                  fontSize: 10,
                  fontWeight: 700,
                  padding: '4px 8px',
                  background: fam.risk === 'CRITICAL' || fam.threat_level === 'CRITICAL' ? 'rgba(248, 113, 113, 0.2)' : 'rgba(251, 191, 36, 0.2)',
                  border: fam.risk === 'CRITICAL' || fam.threat_level === 'CRITICAL' ? '1px solid rgba(248, 113, 113, 0.4)' : '1px solid rgba(251, 191, 36, 0.4)',
                  borderRadius: 3,
                  color: fam.risk === 'CRITICAL' || fam.threat_level === 'CRITICAL' ? '#f87171' : '#fbbf24'
                }}>
                  {fam.risk || fam.threat_level}
                </span>
                <button
                  onClick={() => handleExportCaseFile(fam)}
                  style={{
                    fontFamily: 'var(--font-mono)',
                    fontSize: 10,
                    padding: '4px 8px',
                    background: 'rgba(0, 217, 255, 0.2)',
                    border: '1px solid rgba(0, 217, 255, 0.4)',
                    borderRadius: 3,
                    color: '#00d9ff',
                    cursor: 'pointer',
                    transition: 'all 0.2s'
                  }}
                  onMouseOver={(e) => {
                    e.target.style.background = 'rgba(0, 217, 255, 0.4)';
                  }}
                  onMouseOut={(e) => {
                    e.target.style.background = 'rgba(0, 217, 255, 0.2)';
                  }}
                >
                  ↓ EXPORT
                </button>
              </div>
            </div>

            {(fam.insights && fam.insights.length > 0) && (
              <div style={{ fontSize: 10, color: 'var(--text-secondary)', fontFamily: 'var(--font-mono)', marginTop: 8, paddingTop: 8, borderTop: '1px solid rgba(0,217,255,0.1)' }}>
                {fam.insights[fam.insights.length - 1]}
              </div>
            )}
          </div>
        ))
      )}
    </div>
  );
}
